SnippetVault.UI/ViewModels/AccountDetailsViewModel.cs
using Microsoft.AspNetCore.Mvc;
using SnippetVault.Core.DTO.ApplicationUserDTOs;
using SnippetVault.Core.Validators;
using System.ComponentModel.DataAnnotations;

namespace SnippetVault.UI.ViewModels
{
    public class AccountDetailsViewModel
    {
        public UpdateAccountDTO? UpdateAccountDTO { get; set; }

        public int SnippetsCount { get; set; }
        public int StarsCount { get; set; }
        public int CommentsCount { get; set; }
        public int CommentLikesCount { get; set; }
    }
}

SnippetVault.UI/ViewModels/SnippetDetailsViewModel.cs
using SnippetVault.Core.DTO.CommentDTOs;
using SnippetVault.Core.DTO.SnippetDTOs;

namespace SnippetVault.UI.ViewModels
{
    public class SnippetDetailsViewModel
    {
        public SnippetResponse? SnippetResponse{ get; set; }
        public bool Owner { get; set; }

        public List<CommentResponse>? SnippetComments { get; set; }
    }
}

SnippetVault.UI/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using SnippetVault.Core.Domain.IdentityEntities;
using SnippetVault.Core.ServiceContracts;
using SnippetVault.Core.Services;
using System.Text;

enum LoginStatus
{
    SUCCESS,
    FAILURE,
    EMAIL_NOT_CONFIRMED
}

namespace SnippetVault.UI.Controllers
{
    [Route("[controller]")]
    public partial class AccountController : Controller
    {
        private readonly ApplicationUserManager _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IConfiguration _configuration;
        private readonly IEmailService _emailService;

        public AccountController(ApplicationUserManager userManager, IConfiguration configuration,
            SignInManager<ApplicationUser> signInManager, IEmailService emailService)
        {
            _userManager = userManager;
            _configuration = configuration;
            _signInManager = signInManager;
            _emailService = emailService;
        }
        public async Task<TimeSpan> SendConfirmationEmail(ApplicationUser user)
        {
            var timeDiff = await _userManager.GetEmailConfirmTimeDiff(user.Id);
            var remainingTime = new TimeSpan(0, 10, 0) - timeDiff;

            if (remainingTime <= TimeSpan.Zero)
            {
                var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                byte[] tokenGeneratedBytes = Encoding.UTF8.GetBytes(token);
                token = WebEncoders.Base64UrlEncode(tokenGeneratedBytes);
                var confirmUrl = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/account/confirmemail";
                await _emailService.SendConfirmationEmail(confirmUrl, user.Email, token);
                var userId = await _userManager.GetUserIdAsync(user);
                await _userManager.UpdateEmailConfirmSentDate(Guid.Parse(userId));

                return TimeSpan.Zero;
            }
            else
            {
                return remainingTime;
            }
        }
    }
}

SnippetVault.UI/Controllers/SnippetsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using SnippetVault.Core.DTO.CommentDTOs;
using SnippetVault.Core.DTO.SnippetDTOs;
using SnippetVault.Core.DTO.StarDTOs;
using SnippetVault.Core.Helpers;
using SnippetVault.Core.ServiceContracts;
using SnippetVault.UI.Filters.ActionFilters;
using SnippetVault.UI.ViewModels;

namespace SnippetVault.UI.Controllers
{
    [Route("[controller]")]
    public partial class SnippetsController : Controller
    {
        readonly ISnippetService _snippetService;
        readonly IApplicationUserManager _userManager;
        readonly IStarService _starService;
        readonly ICommentService _commentService;
        readonly ICommentLikeService _commentLikeService;

        public SnippetsController(ISnippetService snippetService, IApplicationUserManager userManager,
            IStarService starService, ICommentService commentService, ICommentLikeService commentLikeService)
        {
            _snippetService = snippetService;
            _userManager = userManager;
            _starService = starService;
            _commentService = commentService;
            _commentLikeService = commentLikeService;
        }
    }
}

SnippetVault.UI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="~/styles/Shared.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    @await RenderSectionAsync("styles", false)
</head>
<body>
    <div class="container">
        <header>
            <nav>
                <ul class="nav-menu-links">
                    <li>
                        <a asp-controller="Snippets" asp-action="Index" active-route-css-class="active-route"
                           additional-routes-to-match="/">All Snippets</a>
                    </li>
                    @if (User.Identity != null && User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-controller="Snippets" asp-action="MySnippets" active-route-css-class="active-route">My Snippets</a>
                        </li>
                        <li>
                            <a asp-controller="Snippets" asp-action="MyStarredSnippets" active-route-css-class="active-route">My Starred Snippets</a>
                        </li>
                    }
                </ul>
                <div class="nav-burger-menu">
                    <button><img src="~/icons/menu_fill0_wght400_grad0_opsz24.svg" /></button>
                    <ul>
                        <li>
                            <a asp-controller="Snippets" asp-action="Index" active-route-css-class="active-route"
                               additional-routes-to-match="/">All Snippets</a>
                        </li>
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a asp-controller="Snippets" asp-action="MySnippets" active-route-css-class="active-route">My Snippets</a>
                            </li>
                            <li>
                                <a asp-controller="Snippets" asp-action="MyStarredSnippets" active-route-css-class="active-route">My Starred Snippets</a>
                            </li>
                        }
                    </ul>
                </div>
            </nav>
            <nav>
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="userNameLabel">@User.Identity.Name</li>
                        <li><a asp-controller="Account" asp-action="Details" active-route-css-class="active-route">Details</a></li>
                        <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Login" active-route-css-class="active-route">Login</a></li>
                        <li><a asp-controller="Account" asp-action="Register" active-route-css-class="active-route">Register</a></li>
                    }
                </ul>
            </nav>
        </header>

        @RenderBody()
        <footer>
            Created by <a href="https://waquwex.github.io">&nbsp;waquwex</a>&nbspwith ASP.NET Core MVC
        </footer>
    </div>
    <script src="~/scripts/libs/jquery/jquery.min.js"></script>
    <script>
        let menuActive = false;
        let hamburgerMenuButton = document.querySelector(".nav-burger-menu > button");
        let hamburgerMenuUl = document.querySelector(".nav-burger-menu > ul");

        hamburgerMenuButton.onclick = () => {
            if (!menuActive) {
                menuActive = true;
                hamburgerMenuUl.style.display = "flex";
                hamburgerMenuButton.style.backgroundColor = "red";
                $(hamburgerMenuUl).animate({
                    height: (hamburgerMenuUl.childElementCount * 38 + 5) + "px"
                }, 350, function () {
                    // Animation complete.
                });
            }
            else {
                menuActive = false;
                hamburgerMenuButton.style.backgroundColor = "transparent";
                $(hamburgerMenuUl).animate({
                    height: "0px"
                }, 350, function () {
                    hamburgerMenuUl.style.display = "none";
                });
            }
        }
    </script>
    @await RenderSectionAsync("scripts", false)
</body>
</html>

SnippetVault.UI/Views/Shared/_Snippet.cshtml
@using SnippetVault.Core.DTO.SnippetDTOs;
@model SnippetResponse

<div class="snippet" id="@Model.SnippetId">
    <div class="data-field">
        <div class="icon">
            <img src="~/icons/draft_fill0_wght400_grad0_opsz24.svg" />
        </div>
        <a asp-action="Details" asp-controller="Snippets" asp-route-snippetId="@Model.SnippetId" class="snippet-file-name-read">
                @Model.ApplicationUser.UserName&nbsp;/&nbsp;@Model.SnippetFileName
        </a>
    </div>
    <div class="data-field">
        <div class="icon">
            <img src="~/icons/title_fill0_wght400_grad0_opsz24.svg" />
        </div>
        <div class="snippet-title-read">
            @Model.SnippetTitle
        </div>
    </div>
    <div class="data-field">
        <div class="icon">
            <img src="~/icons/info_fill0_wght400_grad0_opsz24.svg" />
        </div>
        <div class="snippet-description-read">
            @Model.SnippetDescription
        </div>
    </div>
    <div>
        <textarea asp-for="@Model.SnippetBody" class="snippet-body-read"></textarea>
    </div>
    <div class="snippet-footer">
        <div>
            @if (Model.CurrentUserStarStatus)
            {
                <img src="~/icons/star_active_fill0_wght400_grad0_opsz24.svg" />
            }
            else
            {
                <img src="~/icons/star_fill0_wght400_grad0_opsz24.svg" />
            }
            @Model.SnippetStars
        </div>
        <div>
            <img src="~/icons/chat_fill0_wght400_grad0_opsz24.svg" />
            @Model.SnippetCommentCount
        </div>
    </div>
</div>

SnippetVault.UI/Views/Snippets/CreateComment.cshtml
@using SnippetVault.Core.DTO.CommentDTOs
@using SnippetVault.Core.DTO.SnippetDTOs;
@model CommentAddRequest

@{
    var snippetResponse = ViewData["SnippetResponse"] as SnippetResponse;
}

<div class="snippets-container">
    <div class="snippet" id="@snippetResponse.SnippetId">
        <div class="data-field">
            <div class="icon">
                <img src="~/icons/draft_fill0_wght400_grad0_opsz24.svg" />
            </div>
            <div class="snippet-file-name-read">
                @snippetResponse.ApplicationUser.UserName&nbsp;/&nbsp;@snippetResponse.SnippetFileName
            </div>
        </div>
        <div class="data-field">
            <div class="icon">
                <img src="~/icons/title_fill0_wght400_grad0_opsz24.svg" />
            </div>
            <div class="snippet-title-read">
                @snippetResponse.SnippetTitle
            </div>
        </div>
        <div class="data-field">
            <div class="icon">
                <img src="~/icons/info_fill0_wght400_grad0_opsz24.svg" />
            </div>
            <div class="snippet-description-read">
                @snippetResponse.SnippetDescription
            </div>
        </div>
        <div>
            <textarea asp-for="@snippetResponse.SnippetBody" class="snippet-body-read"></textarea>
        </div>
        <div class="snippet-footer">
            @if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                <a asp-action="Star" asp-controller="Snippets" asp-route-snippetId="@snippetResponse.SnippetId">
                    @if (snippetResponse.CurrentUserStarStatus)
                    {
                        <img src="~/icons/star_active_fill0_wght400_grad0_opsz24.svg" />
                    }
                    else
                    {
                        <img src="~/icons/star_fill0_wght400_grad0_opsz24.svg" />
                    }

                    @snippetResponse.SnippetStars
                </a>
            }
            else
            {
                <div>
                    <img src="~/icons/star_fill0_wght400_grad0_opsz24.svg" />
                    @snippetResponse.SnippetStars
                </div>
            }
            <div>
                <img src="~/icons/chat_fill0_wght400_grad0_opsz24.svg" />
                @snippetResponse.SnippetCommentCount
            </div>
        </div>
    </div>

    <h1>Create Comment</h1>
    <div class="comment">
        <form asp-action="CreateComment" asp-controller="Snippets" method="post">
            <input type="hidden" asp-for="CommentSnippetId" />
            <div class="form-field">
                <textarea asp-for="CommentBody" class="comment-body"></textarea>
                <span class="error" asp-validation-for="CommentBody"></span>
            </div>
            <div class="actions">
                <button class="button"><img src="~/icons/add_fill0_wght400_grad0_opsz24.svg" /><span>Create</span></button>
                <a asp-action="Details" asp-controller="Snippets" asp-route-snippetId="@snippetResponse.SnippetId" class="button">
                    <img src="~/icons/cancel_fill0_wght400_grad0_opsz24.svg" />
                    <span>Discard</span></a>
            </div>
        </form>
    </div>
</div>

@section styles
{
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <link href="~/styles/snippets.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/scripts/libs/codemirror5/lib/codemirror.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/selection/active-line.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/loadmode.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/simple.js"></script>
    <script src="~/scripts/libs/codemirror5/mode/meta.js"></script>

    <script src="~/scripts/SetupReadOnlySnippet.js"></script>

    <script>
        window.addEventListener("load", () => {
            setupCommentBodyTextArea();
        });

        let setupCommentBodyTextArea = () => {
            let sd = document.getElementsByClassName("comment-body")[0];

            const minHeight = 100;

            sd.setAttribute("style", "height:" + 100 + "px;overflow-y:hidden;");

            sd.oninput = (event) => {
                sd.style.height = 0;

                if (sd.scrollHeight < 100) {
                    sd.style.height = "100px";
                } else {
                    sd.style.height = sd.scrollHeight + "px";
                }
            }
        }
    </script>
}

SnippetVault.UI/Views/Snippets/CreateSnippet.cshtml
@using SnippetVault.Core.DTO.SnippetDTOs;
@model SnippetAddRequest

<div class="snippets-container">
    <h1>Create Snippet</h1>
    <div class="snippet">
        <form asp-action="CreateSnippet" asp-controller="Snippets" method="post">
            <div class="form-field">
                <label asp-for="SnippetTitle">Title</label>
                <input asp-for="SnippetTitle" />
                <span class="error" asp-validation-for="SnippetTitle"></span>
            </div>
            <div class="form-field">
                <label asp-for="SnippetDescription">Description</label>
                <textarea class="snippet-description" asp-for="SnippetDescription" rows="1"></textarea>
                <span class="error" asp-validation-for="SnippetDescription"></span>
            </div>
            <div class="form-field">
                <label asp-for="SnippetFileName">File Name with extension</label>
                <input class="snippet-file-name" asp-for="SnippetFileName" />
                <span class="error" asp-validation-for="SnippetFileName"></span>
            </div>
            <div class="form-field">
                <label asp-for="SnippetBody">Code</label>
                <textarea class="snippet-body" asp-for="SnippetBody"></textarea>
                <span class="error" asp-validation-for="SnippetBody"></span>
            </div>
            <button class="form-button">
                Create
            </button>
        </form>
    </div>
</div>

@section styles
{
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <link href="~/styles/snippets.css" rel="stylesheet" />
    <link href="~/styles/snippets_createsnippet.css" rel="stylesheet" />
}


@section scripts
{
    <script src="~/scripts/libs/codemirror5/lib/codemirror.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/selection/active-line.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/loadmode.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/simple.js"></script>
    <script src="~/scripts/libs/codemirror5/mode/meta.js"></script>
    <script src="~/scripts/SetupSnippet.js"></script>
}

SnippetVault.UI/Views/Snippets/Edit.cshtml
@using SnippetVault.Core.DTO.SnippetDTOs;
@model SnippetUpdateRequest

<div class="snippets-container">
    <h1>Edit Snippet</h1>
    <div class="snippet">
        <form asp-action="Edit" asp-controller="Snippets" method="post">
            <input type="hidden" asp-for="SnippetId" />
            <div class="form-field">
                <label asp-for="SnippetTitle">Title</label>
                <input asp-for="SnippetTitle" />
                <span class="error" asp-validation-for="SnippetTitle"></span>
            </div>
            <div class="form-field">
                <label asp-for="SnippetDescription">Description</label>
                <textarea class="snippet-description" asp-for="SnippetDescription" rows="1"></textarea>
                <span class="error" asp-validation-for="SnippetDescription"></span>
            </div>
            <div class="form-field">
                <label asp-for="SnippetFileName">File Name with extension</label>
                <input class="snippet-file-name" asp-for="SnippetFileName" />
                <span class="error" asp-validation-for="SnippetFileName"></span>
            </div>
            <div class="form-field">
                <label asp-for="SnippetBody">Code</label>
                <textarea class="snippet-body" asp-for="SnippetBody"></textarea>
                <span class="error" asp-validation-for="SnippetBody"></span>
            </div>
            <button class="form-button">
                Edit
            </button>
        </form>
    </div>
</div>


@section styles
{
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <link href="~/styles/snippets.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/scripts/libs/codemirror5/lib/codemirror.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/selection/active-line.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/loadmode.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/simple.js"></script>
    <script src="~/scripts/libs/codemirror5/mode/meta.js"></script>
    <script src="~/scripts/SetupSnippet.js"></script>
}

SnippetVault.UI/Views/Snippets/EditComment.cshtml
@using SnippetVault.Core.DTO.CommentDTOs
@using SnippetVault.Core.DTO.SnippetDTOs;
@model CommentUpdateRequest

@{
    var snippetResponse = ViewData["SnippetResponse"] as SnippetResponse;
}

<div class="snippets-container">
    <div class="snippet" id="@snippetResponse.SnippetId">
        <div class="data-field">
            <div class="icon">
                <img src="~/icons/draft_fill0_wght400_grad0_opsz24.svg" />
            </div>
            <div class="snippet-file-name-read">
                @snippetResponse.ApplicationUser.UserName&nbsp;/&nbsp;@snippetResponse.SnippetFileName
            </div>
        </div>
        <div class="data-field">
            <div class="icon">
                <img src="~/icons/title_fill0_wght400_grad0_opsz24.svg" />
            </div>
            <div class="snippet-title-read">
                @snippetResponse.SnippetTitle
            </div>
        </div>
        <div class="data-field">
            <div class="icon">
                <img src="~/icons/info_fill0_wght400_grad0_opsz24.svg" />
            </div>
            <div class="snippet-description-read">
                @snippetResponse.SnippetDescription
            </div>
        </div>
        <div>
            <textarea asp-for="@snippetResponse.SnippetBody" class="snippet-body-read"></textarea>
        </div>
        <div class="snippet-footer">
            @if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                <a asp-action="Star" asp-controller="Snippets" asp-route-snippetId="@snippetResponse.SnippetId">
                    @if (snippetResponse.CurrentUserStarStatus)
                    {
                        <img src="~/icons/star_active_fill0_wght400_grad0_opsz24.svg" />
                    }
                    else
                    {
                        <img src="~/icons/star_fill0_wght400_grad0_opsz24.svg" />
                    }

                    @snippetResponse.SnippetStars
                </a>
            }
            else
            {
                <div>
                    <img src="~/icons/star_fill0_wght400_grad0_opsz24.svg" />
                    @snippetResponse.SnippetStars
                </div>
            }
            <div>
                <img src="~/icons/chat_fill0_wght400_grad0_opsz24.svg" />
                @snippetResponse.SnippetCommentCount
            </div>
        </div>
    </div>

    <h1>Edit Comment</h1>
    <div class="comment">
        <form asp-action="EditComment" asp-controller="Snippets" method="post">
            <input type="hidden" asp-for="CommentSnippetId" />
            <input type="hidden" asp-for="CommentId" />
            <div class="form-field">
                <textarea asp-for="CommentBody" class="comment-body"></textarea>
                <span class="error" asp-validation-for="CommentBody"></span>
            </div>
            <div class="actions">
                <button class="button"><img src="~/icons/edit_fill0_wght400_grad0_opsz24.svg" /><span>Edit</span></button>
                <a asp-action="Details" asp-controller="Snippets" asp-route-snippetId="@snippetResponse.SnippetId" class="button">
                    <img src="~/icons/cancel_fill0_wght400_grad0_opsz24.svg" /><span>Discard</span></a>
            </div>
        </form>
    </div>
</div>

@section styles
{
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <link href="~/styles/snippets.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/scripts/libs/codemirror5/lib/codemirror.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/selection/active-line.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/loadmode.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/simple.js"></script>
    <script src="~/scripts/libs/codemirror5/mode/meta.js"></script>

    <script src="~/scripts/SetupReadOnlySnippet.js"></script>

    <script>
        window.addEventListener("load", () => {
            setupCommentBodyTextArea();
        });

        let setupCommentBodyTextArea = () => {
            let sd = document.getElementsByClassName("comment-body")[0];

            const minHeight = 100;

            sd.setAttribute("style", "height:" + 100 + "px;overflow-y:hidden;");

            sd.oninput = (event) => {
                sd.style.height = 0;

                if (sd.scrollHeight < 100) {
                    sd.style.height = "100px";
                } else {
                    sd.style.height = sd.scrollHeight + "px";
                }
            }
        }
    </script>
}

SnippetVault.UI/Views/Snippets/Index.cshtml
@using SnippetVault.Core.DTO.SnippetDTOs;
@model List<SnippetResponse>

<div class="snippets-container">
    <h1>Latest Snippets</h1>
    @if (Model.Count() == 0)
    {
        <div>
            <p>Nothing to display</p>
        </div>
    }
    else
    {
        foreach (var snippetResponse in Model)
        {
            @await Html.PartialAsync("_Snippet", snippetResponse)
        }

        <div>
            @if (ViewBag.IsItFirstPage == true)
            {
                <div class="paging-button disabled">Newer</div>
            }
            else
            {
                <a class="paging-button" asp-controller="Snippets" asp-action="Index" asp-route-newer="true"
                   asp-route-pivotDateTimeTicks="@Model[0].SnippetCreatedDateTime.Value.Ticks"
                   asp-route-pivotId="@Model[0].SnippetId">Newer</a>
            }

            @if (ViewBag.IsItLastPage == true)
            {
                <div class="paging-button disabled">Older</div>
            }
            else
            {
                <a class="paging-button" asp-controller="Snippets" asp-action="Index" asp-route-newer="false"
                   asp-route-pivotDateTimeTicks="@Model[Model.Count - 1].SnippetCreatedDateTime.Value.Ticks"
                   asp-route-pivotId="@Model[Model.Count - 1].SnippetId">Older</a>
            }
        </div>
    }
</div>



@section styles
{
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <link href="~/styles/snippets.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/scripts/libs/codemirror5/lib/codemirror.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/selection/active-line.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/loadmode.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/simple.js"></script>
    <script src="~/scripts/libs/codemirror5/mode/meta.js"></script>
    <script src="~/scripts/SetupReadOnlySnippet.js"></script>
}

SnippetVault.UI/Views/Snippets/MySnippets.cshtml
@using SnippetVault.Core.DTO.SnippetDTOs;
@model List<SnippetResponse>

<div class="snippets-container">
    <div class="actions">
        <a asp-action="CreateSnippet" asp-controller="Snippets" class="button"><img src="~/icons/add_fill0_wght400_grad0_opsz24.svg" /><span>Create a Snippet</span></a>
    </div>
    <div>
        @if (Model.Count() == 0)
        {
            <div>
                You don't have any snippets yet
            </div>
        }
        else
        {
            foreach (var snippetResponse in Model)
            {
                @await Html.PartialAsync("_Snippet", snippetResponse)
            }

            <div>
                @if (ViewBag.IsItFirstPage == true)
                {
                    <div class="paging-button disabled">Newer</div>
                }
                else
                {
                    <a class="paging-button" asp-controller="Snippets" asp-action="MySnippets" asp-route-newer="true"
                       asp-route-pivotDateTimeTicks="@Model[0].SnippetCreatedDateTime.Value.Ticks"
                       asp-route-pivotId="@Model[0].SnippetId">Newer</a>
                }

                @if (ViewBag.IsItLastPage == true)
                {
                    <div class="paging-button disabled">Older</div>
                }
                else
                {
                    <a class="paging-button" asp-controller="Snippets" asp-action="MySnippets" asp-route-newer="false"
                       asp-route-pivotDateTimeTicks="@Model[Model.Count - 1].SnippetCreatedDateTime.Value.Ticks"
                       asp-route-pivotId="@Model[Model.Count - 1].SnippetId">Older</a>
                }
            </div>
        }
    </div>
</div>

@section styles
    {
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <link href="~/styles/snippets.css" rel="stylesheet" />
    <link href="~/styles/snippets_mysnippets.css" rel="stylesheet" />
    <link href="~/scripts/libs/codemirror5/lib/codemirror.css" rel="stylesheet" />
    <style>
        .CodeMirror {
            border: 1px solid #222;
            border-radius: 3px;
            height: auto;
        }

        .CodeMirror-scroll {
            height: 50px;
        }

    </style>
        }

@section scripts
{
    <script src="~/scripts/libs/codemirror5/lib/codemirror.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/selection/active-line.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/loadmode.js"></script>
    <script src="~/scripts/libs/codemirror5/addon/mode/simple.js"></script>
    <script src="~/scripts/libs/codemirror5/mode/meta.js"></script>
    <script src="~/scripts/SetupReadOnlySnippet.js"></script>
}